### ISSUE TITLE
First call results in UnhandledPromiseRejectionWarning. Any further calls are successful

### ISSUE THREAD

**Issue by sebastianspross** [mattdavis90/node-tado-client#7]
Version: ^0.6.2
Used in typescript express application

```javascript
app.get('/', (req, res) => {
  tado.login('username', 'password');
  tado.getMe().then(resp => { console.log(resp); });
  res.send("done");
});
```

any **first** call of this function results in:

```bash
(node:23056) UnhandledPromiseRejectionWarning: Error: Not yet logged in
    at C:\repos\kassandra\control-pane\tado\node_modules\node-tado-client\index.js:88:24
    at new Promise (<anonymous>)
    at Tado.apiCall (C:\repos\kassandra\control-pane\tado\node_modules\node-tado-client\index.js:71:16)
    at Tado.getMe (C:\repos\kassandra\control-pane\tado\node_modules\node-tado-client\index.js:94:21)
    at C:\repos\kassandra\control-pane\tado\src\index.ts:9:8
    at Layer.handle [as handle_request] (C:\repos\kassandra\control-pane\tado\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\repos\kassandra\control-pane\tado\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\repos\kassandra\control-pane\tado\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\repos\kassandra\control-pane\tado\node_modules\express\lib\router\layer.js:95:5)
    at C:\repos\kassandra\control-pane\tado\node_modules\express\lib\router\index.js:281:22
(node:23056) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 
2)
(node:23056) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

after this initial call any following hit of this functions works like a charm.

**Comment by mattdavis90** [comment]
Hi, there appears to be a slight error in the readme. The login method returns a promise that needs handling. Your code should look something like this

```
app.get('/', (req, res) => {
    tado.login('username', 'password').then(()=>{
        tado.getMe().then(resp => {
            console.log(resp);
        });
        res.send("done");
    });
});
```

**Comment by sebastianspross** [comment]
great! it works. so any call has to be wrapped into a tado.login() right?

**Comment by mattdavis90** [comment]
Hi, not necessarily. The tado object caches the token and will refresh it when required so as long as you can guarantee that a successful login has happened prior to calls then you're good.

**Comment by mattdavis90** [comment]
I've update the README so closing this now. Thanks
